# Generated by Django 4.1.7 on 2023-05-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_pricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist_percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upordown', models.CharField(default='Markup', max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('roundoffto', models.CharField(default='Never mind', max_length=100)),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='Pricelist_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customrate', models.IntegerField()),
                ('itemdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.itemtable')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pricelist')),
            ],
        ),
    ]
