# Generated by Django 4.1.7 on 2023-05-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_pricelist_percentage_pricelist_individual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricelist_percentage',
            new_name='Pricelist1_percentage',
        ),
        migrations.RenameModel(
            old_name='Pricelist_individual',
            new_name='Pricelist2_individual',
        ),
        migrations.RenameField(
            model_name='pricelist1_percentage',
            old_name='pricelist',
            new_name='pricelist1',
        ),
        migrations.RenameField(
            model_name='pricelist2_individual',
            old_name='pricelist',
            new_name='pricelist2',
        ),
    ]
