# Generated by Django 4.1.7 on 2023-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_remove_pricelist2_individual_itemdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='roundoffto',
            field=models.CharField(default='Never mind', max_length=100),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='upordown',
            field=models.CharField(default='Markup', max_length=100),
        ),
        migrations.DeleteModel(
            name='pricelist1_percentage',
        ),
    ]
