# Generated by Django 4.1.7 on 2023-05-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_rename_pricelist_percentage_pricelist1_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='pricelist1_percentage',
            name='pricelist1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pricelist'),
        ),
        migrations.AlterField(
            model_name='pricelist2_individual',
            name='itemdetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.itemtable'),
        ),
        migrations.AlterField(
            model_name='pricelist2_individual',
            name='pricelist2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pricelist'),
        ),
    ]
