# Generated by Django 4.1.7 on 2023-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_pricelist_percentage_pricelist_roundoffto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist2_individual',
            name='customrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
