# Generated by Django 4.1.7 on 2023-05-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_alter_pricelist_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist1_percentage',
            name='pricelist1',
        ),
        migrations.RemoveField(
            model_name='pricelist2_individual',
            name='itemdetails',
        ),
        migrations.RemoveField(
            model_name='pricelist2_individual',
            name='pricelist2',
        ),
        migrations.DeleteModel(
            name='Pricelist',
        ),
        migrations.DeleteModel(
            name='Pricelist1_percentage',
        ),
        migrations.DeleteModel(
            name='Pricelist2_individual',
        ),
    ]
