# Generated by Django 4.1.7 on 2023-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_alter_pricelist2_individual_customrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist2_individual',
            name='customrate',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
