# Generated by Django 4.1.7 on 2023-05-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_alter_pricelist2_individual_customrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='roundoffto',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='upordown',
        ),
        migrations.CreateModel(
            name='pricelist1_percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upordown', models.CharField(default='Markup', max_length=100)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('roundoffto', models.CharField(default='Never mind', max_length=100)),
                ('pricelist1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pricelist')),
            ],
        ),
    ]
