# Generated by Django 4.1.7 on 2023-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_remove_pricelist_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='types',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Purchase', 'Purchase')], default='Sales', max_length=10),
        ),
    ]
