# Generated by Django 4.1.7 on 2023-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_alter_pricelist_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pricelist2_individual',
            new_name='pricelist_individual',
        ),
        migrations.RenameField(
            model_name='pricelist_individual',
            old_name='pricelist2',
            new_name='pricelist1',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='roundoffto',
            field=models.CharField(default='Never mind', max_length=100),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='upordown',
            field=models.CharField(default='Markup', max_length=100),
        ),
        migrations.DeleteModel(
            name='pricelist1_percentage',
        ),
    ]
